### ISSUE TITLE
can not find env_CF_MIMO_noGroup.py

### ISSUE THREAD

**Issue by Zhuxz111** [YiyangZYY/MARL-based_Joint_Precoding_and_Phase_Shift_Optimization_for_RIS-aided_Cell-Free_Massive_MIMO_Systems#1]
when i run main.py, there is an error: could not find module env_CF_MIMO_noGroup

**Comment by YiyangZYY** [comment]
Many thanks for pointing out the bug. I have updated the 'main.py' for the import modules.

**Comment by YiyangZYY** [comment]
Moreover, as outlined in the README, users should commence by configuring the environment in "env/env_CF_MIMO.py" before running the code. The primary task involves completing the "compute_reward" function on line 137 and the "step" function on line 140. In my paper, I have designated the sum-SE as the reward; however, you will need to adapt it to align with your specific requirements.

**Comment by YiyangZYY** [comment]
And I will update the repo to the lastst version of my code soon
