### ISSUE TITLE
Reward (Objective function) calculation is missing

### ISSUE THREAD

**Issue by probot-codes** [YiyangZYY/MARL-based_Joint_Precoding_and_Phase_Shift_Optimization_for_RIS-aided_Cell-Free_Massive_MIMO_Systems#2]
Dear Authors,
I would like to know that where did you calculate the reward function. 
I am unable to find the sum spectral efficiency.
In main. py file, Line 200 utilises `a_EE,a_SE = env._compute_EE_()`, but `compute_EE` is not explicitly defined.

Regards.

**Comment by YiyangZYY** [comment]
I am sorry that the repo is SOLELY UTILIZED FOR DEMONSTRATION PURPOSES because our work is still being extended. The full version of the code will be reuploaded once the extended work and paper is published. Many thanks for your interest in our work :)
