### ISSUE TITLE
env. function error

### ISSUE THREAD

**Issue by Miraclebv** [YiyangZYY/MARL-based_Joint_Precoding_and_Phase_Shift_Optimization_for_RIS-aided_Cell-Free_Massive_MIMO_Systems#3]
Dear author，
   
   The code you recently shared has been modified to env. in the main function loading, but it still seems to have errors when running directly.

   
   Wishing you all the best in your work.

**Comment by YiyangZYY** [comment]
Thank you for pointing out the issue. However, as stated in the README, this repository is i**ntended for presentation purposes only** and **cannot be trained directly**. You will need to modify the environment to suit your needs (which might be challenging for beginners). I recommend using my other repository, https://github.com/YiyangZYY/MARL_based_Optimization_for_Cell-Free_Massive_MIMO_Systems, as it is more suitable for direct training and running after setting up the requirements. Additionally, it provides a framework that is more readable and user-friendly than this one. :)

**Comment by Miraclebv** [comment]
Thank you again for the author's suggestion. Best wishes.

**Comment by YiyangZYY** [comment]
:)

**Comment by YiyangZYY** [comment]
BTW, if you know Enyu, maybe we can discuss the code directly through WeChat :>
